FROM node:18-alpine AS build

RUN npm install -g pnpm

WORKDIR /

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm run build

# Takes the default Nginx image as the base image
FROM nginx:alpine

# Copy the config files
ADD ./conf/ /etc/nginx/
# Clears the static files
RUN rm -rf /usr/share/nginx/html
# Copy the static web content
ADD ./dist /usr/share/nginx/html
# Suggests to bind port 80 to any port of the host system
EXPOSE 80